// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwKpYCbbvj_rnGldy0nQTgdwBfsanDiEw',
    appId: '1:834083850702:web:b55bde14a5c14ebee6439f',
    messagingSenderId: '834083850702',
    projectId: 'sign-up-e89de',
    authDomain: 'sign-up-e89de.firebaseapp.com',
    storageBucket: 'sign-up-e89de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5QWj7UjWzQ5nsxmC2l4iy2fui3Ka5btY',
    appId: '1:834083850702:android:d25a21dc47a49debe6439f',
    messagingSenderId: '834083850702',
    projectId: 'sign-up-e89de',
    storageBucket: 'sign-up-e89de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfRxy-04A8UNfqYlqWrP_4STOCBylH84A',
    appId: '1:834083850702:ios:845b924eeb67a341e6439f',
    messagingSenderId: '834083850702',
    projectId: 'sign-up-e89de',
    storageBucket: 'sign-up-e89de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfRxy-04A8UNfqYlqWrP_4STOCBylH84A',
    appId: '1:834083850702:ios:845b924eeb67a341e6439f',
    messagingSenderId: '834083850702',
    projectId: 'sign-up-e89de',
    storageBucket: 'sign-up-e89de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwKpYCbbvj_rnGldy0nQTgdwBfsanDiEw',
    appId: '1:834083850702:web:5e3ac22532419d66e6439f',
    messagingSenderId: '834083850702',
    projectId: 'sign-up-e89de',
    authDomain: 'sign-up-e89de.firebaseapp.com',
    storageBucket: 'sign-up-e89de.firebasestorage.app',
  );
}